### ISSUE TITLE
Focus moved from chat-prompt to chat window after activating macro

### ISSUE THREAD

**Issue by folken88** [League-of-Foundry-Developers/fvtt-advanced-macros#38] opened 2022-09-22 05:05 UTC
FVTT V10, 286
Tested with pathfinder system .82.2
All mods off except advanced macros

After activating any skill/spell macro, the focus shifts from the chat prompt, to the chat window itself. Previously the cursor/focus would stay in the chat prompt.

Causes some extra work for blind players, who love this mod + functionality. 🍡

**Comment by mclemente** [comment] 2022-09-22 05:12
I can't reproduce that. Give me a macro example.

**Comment by folken88** [comment] 2022-09-22 05:45
PF1: This one exhibits the problem, a perception macro that is
actor-agnostic:
actor.rollSkill("per");


PF1: This one does not exhibit the problem, an item macro that specifies
actor + item:
const item = await fromUuid("Actor.kkilRckwr9JVRKVh.Item.jIyMPL1PaQQVckL8");
return item.use({skipDialog: true});

I only see it doing this in PF1, my starfinder macros do not have the
problem. Perhaps I should make it an issue there instead or in addition to
this issue?
ty!!

**Comment by mclemente** [comment] 2022-09-22 16:17
Ok, the issue is that `actor.rollSkill("per");` normally opens a dialog (to roll normally, take 10 or take 20) that takes the focus, but it catches the Enter input from the `/` command and instantly closing it and rolling.
You can fix that by adding a `{ skipDialog: true }` parameter to those checks, example: `actor.rollSkill("per", { skipDialog: true })`.
There's also the `Skip Action Prompts` setting under the PF1 settings, but it doesn't seem to be working for macro calls for some reason.
Fixing it on Advanced Macros wouldn't be a permanent fix, since PF1's code could be changed regardless. I suggest you open an issue on the PF1 repo asking to change/fix that setting's behavior to add `skipDialog` to its rollOptions if the setting is on, so you don't need to add `{ skipDialog: true }` to every single macro.

**Comment by folken88** [comment] 2022-09-22 21:09
Thank you for this! I have skipdialogue in some of my macros but I've found
it unreliable. Obviously skipdialog is ideal for the blind player and he
has it set "on" in his client config but - as you say - it does not appear
to rule over everything!

Also, if there's any way we could help, we would gladly do so..... Your mod
is essential!

**Comment by mclemente** [comment] 2022-09-22 22:24
What I can fix: whenever a dialog prompt closes, focus back to the chat. This won't solve your problem.

What I can't fix:
- Enter being captured when the prompt is rendered. That would either require the Foundry devs to change it.
- PF1's dialog prompt opening and your players having to click a button in that prompt for the action to be rolled. 

I can't monkey-patch PF1's functions like I can with Foundry's. You need to have skipDialog on your macros or have the PF1 devs improve the Skip Action Prompts setting.

**Comment by folken88** [comment] 2022-09-22 22:27
Yep! I've added it to each skill macro. No problem! Really easily done and
then copying it to the other games. I may make a publicly available
compendium of foundry-macros to save other folks time.

**Closed** 2022-11-10 17:45 UTC
